### ISSUE TITLE
?name cloud is throwing an exception

### ISSUE THREAD

**Issue by Japnix** [Japnix/fftcg_parser#6]
`Ignoring exception in command name
Traceback (most recent call last):
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "marcie.py", line 54, in name
    await bot.say('```' + output + '```')
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/btawa/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400)`

**Comment by Japnix** [comment]
Discord API is limited to less than 2000 characters per message.  Hitting an issue where partial matching is causing things like `?name cloud` to trigger on clouds (which has a lot) as well as famfrit and cloud of darkness.

Added a workaround specifically for `cloud` but we will see this issue with summoner as well as other cards with many prints.

Need user input enhancement OR a way to dice up longer outputs into multiple messages in discord.

**Comment by Japnix** [comment]
Added support for regex in searching.  To get cloud a search for ^Cloud$ can be done.
